/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Cliente;

import Controller.ClienteController;
import Controller.Conexao;
import Model.Cliente;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Helio
 */
public class alterarCliente1 extends javax.swing.JPanel {

    /**
     * Creates new form alterarCliente1
     */
    private final Cliente cliente = new Cliente();
    private final Connection con = new Conexao().AbrirConexao();
    private final ClienteController cc = new ClienteController(con);
    
    public alterarCliente1() {
        initComponents();
        
        int index1 = 0;
        for (String listarEstado : cc.listarEstados()) {

            comboBoxEstado.insertItemAt(listarEstado, index1);
            index1++;
        }

        int index2 = 0;
        for (String listarCidade : cc.listarCidades()) {

            comboBoxCidade.insertItemAt(listarCidade, index2);
            index2++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        textFieldIdCliente = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlterar = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        textFieldNomeContato = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        textFieldRazaoSocial = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        textFieldCnpj = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        textFieldEmail = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        textFieldTelefone = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textFieldCep = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        textFieldRua = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jButtonBusca = new javax.swing.JButton();
        botaoLimparBusca = new javax.swing.JButton();
        botaoAlterar = new javax.swing.JButton();
        comboBoxCidade = new javax.swing.JComboBox<>();
        comboBoxEstado = new javax.swing.JComboBox<>();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setBackground(new java.awt.Color(224, 224, 224));
        labelTitulo.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(224, 224, 224));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Alterar Clientes");
        jPanel1.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 980, -1));

        textFieldIdCliente.setEditable(false);
        textFieldIdCliente.setBackground(new java.awt.Color(0, 153, 153));
        textFieldIdCliente.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        textFieldIdCliente.setBorder(null);
        jPanel1.add(textFieldIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 230, -1));

        jComboBox1.setBackground(new java.awt.Color(0, 153, 153));
        jComboBox1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um campo", "Nome", "ID", "Estado", "Cep", "Razão Social", "CNPJ", "E-mail", "Telefone", "Rua", "Cidade" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 370, -1));

        jSeparator1.setBackground(new java.awt.Color(224, 224, 224));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 230, 10));

        jTableAlterar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome Contato", "Razão Social", "CNPJ", "E-mail", "Telefone", "Estado", "Cidade", "Cep", "Rua"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAlterarMouseClicked(evt);
            }
        });
        jTableAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableAlterarKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAlterar);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 490, 250));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel2.setText("Buscar cliente: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 95, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel3.setText("ID: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, -1, -1));

        jTextField2.setBackground(new java.awt.Color(0, 153, 153));
        jTextField2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jTextField2.setBorder(null);
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 370, -1));

        jSeparator2.setBackground(new java.awt.Color(224, 224, 224));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 370, 10));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel4.setText("<html>Nome:<font color=\"red\"><b>*</b></font>");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, -1, -1));

        textFieldNomeContato.setBackground(new java.awt.Color(0, 153, 153));
        textFieldNomeContato.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        textFieldNomeContato.setBorder(null);
        jPanel1.add(textFieldNomeContato, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 230, -1));

        jSeparator3.setBackground(new java.awt.Color(224, 224, 224));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 230, 10));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel5.setText("<html>Razão:<font color=\"red\"><b>*</b></font>");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));

        textFieldRazaoSocial.setBackground(new java.awt.Color(0, 153, 153));
        textFieldRazaoSocial.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        textFieldRazaoSocial.setBorder(null);
        jPanel1.add(textFieldRazaoSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 230, -1));

        jSeparator4.setBackground(new java.awt.Color(224, 224, 224));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 230, 10));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel6.setText("<html>Cnpj:<font color=\"red\"><b>*</b></font>");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, -1, -1));

        textFieldCnpj.setBackground(new java.awt.Color(0, 153, 153));
        textFieldCnpj.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        textFieldCnpj.setBorder(null);
        jPanel1.add(textFieldCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 230, -1));

        jSeparator5.setBackground(new java.awt.Color(224, 224, 224));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, 230, 10));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel7.setText("<html>E-mail:<font color=\"red\"><b>*</b></font>");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, -1, -1));

        textFieldEmail.setBackground(new java.awt.Color(0, 153, 153));
        textFieldEmail.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        textFieldEmail.setBorder(null);
        jPanel1.add(textFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 230, -1));

        jSeparator6.setBackground(new java.awt.Color(224, 224, 224));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 230, 10));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel8.setText("<html>Tel:<font color=\"red\"><b>*</b></font>");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, -1, -1));

        textFieldTelefone.setBackground(new java.awt.Color(0, 153, 153));
        textFieldTelefone.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        textFieldTelefone.setBorder(null);
        jPanel1.add(textFieldTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 230, -1));

        jSeparator7.setBackground(new java.awt.Color(224, 224, 224));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 230, 10));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel9.setText("Estado: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel10.setText("Cidade: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel11.setText("<html>Cep:<font color=\"red\"><b>*</b></font>");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, -1, -1));

        textFieldCep.setBackground(new java.awt.Color(0, 153, 153));
        textFieldCep.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        textFieldCep.setBorder(null);
        jPanel1.add(textFieldCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 230, 20));

        jSeparator10.setBackground(new java.awt.Color(224, 224, 224));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 230, 0));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        jLabel12.setText("<html>Rua:<font color=\"red\"><b>*</b></font> ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, -1, -1));

        textFieldRua.setBackground(new java.awt.Color(0, 153, 153));
        textFieldRua.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        textFieldRua.setBorder(null);
        jPanel1.add(textFieldRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 230, -1));

        jSeparator11.setBackground(new java.awt.Color(224, 224, 224));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 230, 10));

        jButtonBusca.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jButtonBusca.setText("Nova Busca");
        jButtonBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 160, 40));

        botaoLimparBusca.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        botaoLimparBusca.setText("Limpar Pesquisa");
        botaoLimparBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparBuscaActionPerformed(evt);
            }
        });
        jPanel1.add(botaoLimparBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 160, 40));

        botaoAlterar.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        botaoAlterar.setText("Alterar");
        botaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 420, -1, -1));

        comboBoxCidade.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        comboBoxCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione sua cidade" }));
        comboBoxCidade.setBorder(null);
        comboBoxCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCidadeActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 230, 30));

        comboBoxEstado.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        comboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione seu estado" }));
        comboBoxEstado.setBorder(null);
        comboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, 230, -1));

        jSeparator8.setBackground(new java.awt.Color(224, 224, 224));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 230, 10));

        jSeparator12.setBackground(new java.awt.Color(224, 224, 224));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 230, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        if (!"Selecione um campo".equals(jComboBox1.getSelectedItem() + "")) { // Castzinho maroto

            jComboBox1.setVisible(false);
            jTextField2.setVisible(true);
            jSeparator2.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTableAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAlterarMouseClicked

        int[] linha = jTableAlterar.getSelectedRows();

        if (linha.length == 1) {

            try {

                textFieldIdCliente.setText(jTableAlterar.getValueAt(linha[0], 0) + "");
                textFieldNomeContato.setText(jTableAlterar.getValueAt(linha[0], 1) + "");
                textFieldRazaoSocial.setText(jTableAlterar.getValueAt(linha[0], 2) + "");
                textFieldCnpj.setText(jTableAlterar.getValueAt(linha[0], 3) + "");
                textFieldEmail.setText(jTableAlterar.getValueAt(linha[0], 4) + "");
                textFieldTelefone.setText(jTableAlterar.getValueAt(linha[0], 5) + "");
                comboBoxEstado.setSelectedItem(jTableAlterar.getValueAt(linha[0], 6) + "");
                comboBoxCidade.setSelectedItem(jTableAlterar.getValueAt(linha[0], 7) + "");
                textFieldCep.setText(jTableAlterar.getValueAt(linha[0], 8) + "");
                textFieldRua.setText(jTableAlterar.getValueAt(linha[0], 9) + "");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao popular tabela! " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jTableAlterarMouseClicked

    private void jTableAlterarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableAlterarKeyReleased
        // TODO add your handling code here:
        jTableAlterarMouseClicked(null);
    }//GEN-LAST:event_jTableAlterarKeyReleased

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed

        AbstractAction acaoEnter = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {

                try {

                    Connection con = new Conexao().AbrirConexao();
                    ClienteController cc = new ClienteController(con);
                    List<Cliente> cliente = null;

                    switch (jComboBox1.getSelectedItem().toString()) {

                        case "":
                        case "ID":

                        cliente = cc.listarTodosClientes();
                        break;
                        case "Nome":

                        cliente = cc.listarClientesEspecificosNomeContato(jTextField2.getText(), 0);
                        break;
                        case "Estado":

                        cliente = cc.listarClientesEspecificosEstado(jTextField2.getText(), 0);
                        break;
                        case "Cep":

                        cliente = cc.listarClientesEspecificosCep(jTextField2.getText(), 0);
                        break;
                        case "Razão Social":

                        cliente = cc.listarClientesEspecificosRazaoSocial(jTextField2.getText(), 0);
                        break;
                        case "CNPJ":

                        cliente = cc.listarClientesEspecificosCnpj(jTextField2.getText(), 0);
                        break;
                        case "E-mail":

                        cliente = cc.listarClientesEspecificosEmail(jTextField2.getText(), 0);
                        break;
                        case "Telefone":

                        cliente = cc.listarClientesEspecificosTelefone(jTextField2.getText(), 0);
                        break;
                        case "Rua":

                        cliente = cc.listarClientesEspecificosRua(jTextField2.getText(), 0);
                        break;
                        case "Cidade":

                        cliente = cc.listarClientesEspecificosCidade(jTextField2.getText(), 0);
                        break;
                    }
 
                    if (cliente.isEmpty()) {

                        JOptionPane.showMessageDialog(null, "Não existem dados para essa busca");
                    } else {

                        DefaultTableModel dtm = (DefaultTableModel) jTableAlterar.getModel();
                        for (int i = dtm.getRowCount(); i > 0; i--) {

                            dtm.removeRow(i - 1);
                        }

                        for (int i = 0; i < cliente.size(); i++) {

                            dtm.addRow(new Object[]{
                                cliente.get(i).getIdCliente(),
                                cliente.get(i).getNomeContato(),
                                cliente.get(i).getRazaoSocial(),
                                cliente.get(i).getCnpj(),
                                cliente.get(i).getEmail(),
                                cliente.get(i).getTelefone(),
                                cliente.get(i).getEstado(),
                                cliente.get(i).getCidade(),
                                cliente.get(i).getCep(),
                                cliente.get(i).getRua(),});
                    }

                    jTextField2.setText("");
                }

            } catch (HeadlessException ex) {

                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
        };

        AbstractAction acaoF1 = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {

                jComboBox1.setVisible(true);
                jTextField2.setVisible(false);
                jSeparator2.setVisible(false);
            }
        };

        JTextField enter = jTextField2;
        enter.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "acaoEnter");
        enter.getActionMap().put("acaoEnter", acaoEnter);

        JTextField f1 = jTextField2;
        f1.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0), "acaoF1");
        f1.getActionMap().put("acaoF1", acaoF1);
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jButtonBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaActionPerformed
        // TODO add your handling code here:

        //navegarEntreTelas(new listarCliente2());
        jComboBox1.setVisible(true);
        jTextField2.setVisible(false);
        jSeparator2.setVisible(false);
    }//GEN-LAST:event_jButtonBuscaActionPerformed

    private void botaoLimparBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparBuscaActionPerformed
        jTextField2.setText("");
        DefaultTableModel dtm = (DefaultTableModel) jTableAlterar.getModel();
        for (int i = dtm.getRowCount(); i > 0; i--) {
            dtm.removeRow(i - 1);
        }
        textFieldCep.setText("");
        textFieldCnpj.setText("");
        textFieldEmail.setText("");
        textFieldIdCliente.setText("");
        textFieldRazaoSocial.setText("");
        textFieldTelefone.setText("");
        comboBoxCidade.setSelectedItem(0);
        comboBoxEstado.setSelectedItem(0);
        textFieldNomeContato.setText("");
        textFieldRua.setText("");
    }//GEN-LAST:event_botaoLimparBuscaActionPerformed

    private void botaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarActionPerformed
        boolean campoVazio = (textFieldCep.getText().isEmpty()
            ? (textFieldCnpj.getText().isEmpty()
                ? (textFieldEmail.getText().isEmpty()
                    ? (textFieldNomeContato.getText().isEmpty()
                        ? (textFieldRazaoSocial.getText().isEmpty()
                            ? (textFieldRua.getText().isEmpty()
                                ? (textFieldTelefone.getText().isEmpty()) : false) : false) : false) : false) : false) : false);

        if (campoVazio) {

            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!");
        } else {

            try {
                int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente alterar este cadastro?",
                    "Confirmação", JOptionPane.YES_NO_OPTION);//criar uma tela para perguntar se quer ou não excluir
                if (resposta == JOptionPane.YES_NO_OPTION) {

                    cliente.setIdCliente(textFieldIdCliente.getText());
                    cliente.setCep(textFieldCep.getText());
                    cliente.setCidade(comboBoxCidade.getSelectedIndex() + "");
                    cliente.setCnpj(textFieldCnpj.getText());
                    cliente.setEmail(textFieldEmail.getText());
                    cliente.setEstado(comboBoxEstado.getSelectedIndex() + "");
                    cliente.setNomeContato(textFieldNomeContato.getText());
                    cliente.setRazaoSocial(textFieldRazaoSocial.getText());
                    cliente.setRua(textFieldRua.getText());
                    cliente.setTelefone(textFieldTelefone.getText());

                    cc.alterarCliente(cliente, cliente.getIdCliente());
                    javax.swing.table.DefaultTableModel dtm
                    = // para atualizar a tabela
                    (javax.swing.table.DefaultTableModel) jTableAlterar.getModel();

                    dtm.setValueAt(Integer.parseInt(textFieldIdCliente.getText()), jTableAlterar.getSelectedRow(), 0);
                    dtm.setValueAt(textFieldNomeContato.getText(), jTableAlterar.getSelectedRow(), 1);
                    dtm.setValueAt(textFieldRazaoSocial.getText(), jTableAlterar.getSelectedRow(), 2);
                    dtm.setValueAt(textFieldCnpj.getText(), jTableAlterar.getSelectedRow(), 3);
                    dtm.setValueAt(comboBoxCidade.getSelectedItem(), jTableAlterar.getSelectedRow(), 4);
                    dtm.setValueAt(textFieldRua.getText(), jTableAlterar.getSelectedRow(), 5);
                    dtm.setValueAt(comboBoxEstado.getSelectedItem(), jTableAlterar.getSelectedRow(), 6);
                    dtm.setValueAt(textFieldCep.getText(), jTableAlterar.getSelectedRow(), 7);
                    dtm.setValueAt(textFieldEmail.getText(), jTableAlterar.getSelectedRow(), 8);
                    dtm.setValueAt(textFieldTelefone.getText(), jTableAlterar.getSelectedRow(), 9);

                    JOptionPane.showMessageDialog(null, "Usuário  alterado com sucesso");

                }

            } catch (HeadlessException ex) {
                JOptionPane.showMessageDialog(null, "Erro:\n" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_botaoAlterarActionPerformed

    private void comboBoxCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCidadeActionPerformed

    private void comboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxEstadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterar;
    private javax.swing.JButton botaoLimparBusca;
    private javax.swing.JComboBox<String> comboBoxCidade;
    private javax.swing.JComboBox<String> comboBoxEstado;
    private javax.swing.JButton jButtonBusca;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTableAlterar;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField textFieldCep;
    private javax.swing.JTextField textFieldCnpj;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldIdCliente;
    private javax.swing.JTextField textFieldNomeContato;
    private javax.swing.JTextField textFieldRazaoSocial;
    private javax.swing.JTextField textFieldRua;
    private javax.swing.JTextField textFieldTelefone;
    // End of variables declaration//GEN-END:variables
}
