/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Cliente;

import Controller.ClienteController;
import Controller.Conexao;
import Model.Cliente;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Helio
 */
public class alterarCliente extends javax.swing.JPanel {

	/**
	 * Creates new form AlterCliente
	 */
	public alterarCliente() {
		initComponents();
	}

	/**
	 * This method is called from within the
	 * constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The
	 * content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jPanel1 = new javax.swing.JPanel();
            jPanel2 = new javax.swing.JPanel();
            jPanel4 = new javax.swing.JPanel();
            jPanel3 = new javax.swing.JPanel();
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            jTextFieldNomeContato = new javax.swing.JTextField();
            jTextFieldCidade = new javax.swing.JTextField();
            jTextFieldRua = new javax.swing.JTextField();
            jButtonLimpar = new javax.swing.JButton();
            jButtonAlterar = new javax.swing.JButton();
            jLabel9 = new javax.swing.JLabel();
            jLabel10 = new javax.swing.JLabel();
            jLabel11 = new javax.swing.JLabel();
            jLabel12 = new javax.swing.JLabel();
            jTextFieldRazãoSocial = new javax.swing.JTextField();
            jTextFieldCep = new javax.swing.JTextField();
            jLabel13 = new javax.swing.JLabel();
            jTextFieldEmail = new javax.swing.JTextField();
            jLabel14 = new javax.swing.JLabel();
            jComboBoxEstado = new javax.swing.JComboBox();
            jFormattedTextFieldCNPJ = new javax.swing.JFormattedTextField();
            jTextFieldIdcliente = new javax.swing.JTextField();
            jLabel15 = new javax.swing.JLabel();
            jTextFieldTelefone = new javax.swing.JTextField();
            jPanel6 = new javax.swing.JPanel();
            jButtonLimparBusca2 = new javax.swing.JButton();
            jScrollPane3 = new javax.swing.JScrollPane();
            jTable3 = new javax.swing.JTable();
            jLabel17 = new javax.swing.JLabel();
            jTextFieldBusca2 = new javax.swing.JTextField();
            jButtonPesquisar2 = new javax.swing.JButton();

            jPanel1.setBackground(new java.awt.Color(0, 0, 51));

            jPanel2.setBackground(new java.awt.Color(0, 0, 51));

            jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 3, true), "Alterar Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(0, 102, 0))); // NOI18N

            jLabel1.setText("<html>Nome Contato:<font color=\"red\"><b>*</b></font>");

            jLabel2.setText("<html>CNPJ:<font color=\"red\"><b>*</b></font>");

            jLabel5.setText("<html>Cidade:<font color=\"red\"><b>*</b></font>");

            jLabel6.setText("Rua:");

            jLabel7.setText("<html>Telefone:<font color=\"red\"><b>*</b></font>");

            jTextFieldNomeContato.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jTextFieldNomeContatoActionPerformed(evt);
                  }
            });
            jTextFieldNomeContato.addKeyListener(new java.awt.event.KeyAdapter() {
                  public void keyTyped(java.awt.event.KeyEvent evt) {
                        jTextFieldNomeContatoKeyTyped(evt);
                  }
            });

            jTextFieldCidade.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jTextFieldCidadeActionPerformed(evt);
                  }
            });
            jTextFieldCidade.addKeyListener(new java.awt.event.KeyAdapter() {
                  public void keyTyped(java.awt.event.KeyEvent evt) {
                        jTextFieldCidadeKeyTyped(evt);
                  }
            });

            jTextFieldRua.addKeyListener(new java.awt.event.KeyAdapter() {
                  public void keyTyped(java.awt.event.KeyEvent evt) {
                        jTextFieldRuaKeyTyped(evt);
                  }
            });

            jButtonLimpar.setText("Limpar");
            jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButtonLimparActionPerformed(evt);
                  }
            });

            jButtonAlterar.setText("Alterar");
            jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButtonAlterarActionPerformed(evt);
                  }
            });

            jLabel9.setText("<html><font color=\"red\"><b>*</b></font>Campos Obrigatórios");

            jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel10MouseClicked(evt);
                  }
            });

            jLabel11.setText("<html>Estado:<font color=\"red\"><b>*</b></font>:");

            jLabel12.setText("<html>Razão Social:<font color=\"red\"><b>*</b></font>");

            jTextFieldRazãoSocial.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jTextFieldRazãoSocialActionPerformed(evt);
                  }
            });
            jTextFieldRazãoSocial.addKeyListener(new java.awt.event.KeyAdapter() {
                  public void keyTyped(java.awt.event.KeyEvent evt) {
                        jTextFieldRazãoSocialKeyTyped(evt);
                  }
            });

            jTextFieldCep.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jTextFieldCepActionPerformed(evt);
                  }
            });
            jTextFieldCep.addKeyListener(new java.awt.event.KeyAdapter() {
                  public void keyTyped(java.awt.event.KeyEvent evt) {
                        jTextFieldCepKeyTyped(evt);
                  }
            });

            jLabel13.setText("<html>CEP:<font color=\"red\"><b>*</b></font>");

            jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jTextFieldEmailActionPerformed(evt);
                  }
            });
            jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
                  public void keyTyped(java.awt.event.KeyEvent evt) {
                        jTextFieldEmailKeyTyped(evt);
                  }
            });

            jLabel14.setText("<html>E-mail:<font color=\"red\"><b>*</b></font>");

            jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o Estado", "Acre\t ", "Alagoas\t\t ", "Amapá\t\t ", "Amazonas\t\t ", "Bahia\t\t ", "Ceará\t\t ", "Distrito Federal\t\t ", "Espírito Santo\t\t ", "Goiás\t\t ", "Maranhão\t\t ", "Mato Grosso\t\t ", "Mato Grosso do Sul\t\t ", "Minas Gerais\t\t ", "Pará\t\t ", "Paraíba\t\t ", "Paraná\t\t ", "Pernambuco\t ", "Piauí\t ", "Rio de Janeiro ", "Rio Grande do Norte ", "Rio Grande do Sul\t ", "Rondônia", "Roraima ", "Santa Catarina ", "São Paulo\t ", "Sergipe ", "Tocantins" }));
            jComboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jComboBoxEstadoActionPerformed(evt);
                  }
            });

            jFormattedTextFieldCNPJ.setText("  .   .   /    -  ");

            jTextFieldIdcliente.setBackground(new java.awt.Color(204, 204, 204));
            jTextFieldIdcliente.setEnabled(false);
            jTextFieldIdcliente.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jTextFieldIdclienteActionPerformed(evt);
                  }
            });

            jLabel15.setText("Código:");

            jTextFieldTelefone.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jTextFieldTelefoneActionPerformed(evt);
                  }
            });

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                  jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                      .addGap(64, 64, 64)
                                                      .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                      .addContainerGap()
                                                      .addComponent(jLabel6)))
                                          .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jTextFieldIdcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10)
                                    .addContainerGap())
                              .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jButtonLimpar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                    .addComponent(jButtonAlterar)
                                    .addGap(204, 204, 204))
                              .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                              .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(jTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(jTextFieldRazãoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(jFormattedTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(jTextFieldNomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE))))
            );
            jPanel3Layout.setVerticalGroup(
                  jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(19, 19, 19))
                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                          .addComponent(jTextFieldIdcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(jLabel15))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                              .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                          .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(jTextFieldNomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                          .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(jTextFieldRazãoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                          .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(jFormattedTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel6)
                              .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                          .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(jTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                          .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                          .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(jButtonLimpar)
                                          .addComponent(jButtonAlterar)))
                              .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(25, Short.MAX_VALUE))
            );

            jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 3, true));

            jButtonLimparBusca2.setText("Limpar Busca");
            jButtonLimparBusca2.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButtonLimparBusca2ActionPerformed(evt);
                  }
            });

            jTable3.setModel(new javax.swing.table.DefaultTableModel(
                  new Object [][] {

                  },
                  new String [] {
                        "IdCliente", "NomeContato", "RazaoSocial", "Cnpj", "Cidade", "Rua", "Estado", "Cep", "E-mail", "Telefone"
                  }
            ) {
                  boolean[] canEdit = new boolean [] {
                        false, false, false, true, true, true, true, true, true, true
                  };

                  public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                  }
            });
            jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jTable3MouseClicked(evt);
                  }
            });
            jTable3.addKeyListener(new java.awt.event.KeyAdapter() {
                  public void keyReleased(java.awt.event.KeyEvent evt) {
                        jTable3KeyReleased(evt);
                  }
            });
            jScrollPane3.setViewportView(jTable3);

            jLabel17.setText("Buscar Cliente");

            jButtonPesquisar2.setText("Pesquisar");
            jButtonPesquisar2.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButtonPesquisar2ActionPerformed(evt);
                  }
            });

            javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
            jPanel6.setLayout(jPanel6Layout);
            jPanel6Layout.setHorizontalGroup(
                  jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                                .addGap(96, 96, 96)
                                                .addComponent(jButtonLimparBusca2))
                                          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel17))
                                          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                                .addGap(99, 99, 99)
                                                .addComponent(jButtonPesquisar2)))
                                    .addGap(0, 0, Short.MAX_VALUE))
                              .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                          .addComponent(jScrollPane3)
                                          .addComponent(jTextFieldBusca2, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addContainerGap())
            );
            jPanel6Layout.setVerticalGroup(
                  jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldBusca2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimparBusca2)
                        .addContainerGap())
            );

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                  jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel4Layout.setVerticalGroup(
                  jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                  jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel2Layout.setVerticalGroup(
                  jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
            );
      }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeContatoActionPerformed
	    // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeContatoActionPerformed

    private void jTextFieldNomeContatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeContatoKeyTyped
	    if (jTextFieldNomeContato.getText().length() >= 50) {
		    evt.consume();
	    }
    }//GEN-LAST:event_jTextFieldNomeContatoKeyTyped

    private void jTextFieldCidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCidadeKeyTyped
	    if (jTextFieldCidade.getText().length() >= 30) {
		    evt.consume();
	    }
    }//GEN-LAST:event_jTextFieldCidadeKeyTyped

    private void jTextFieldRuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRuaKeyTyped
	    if (jTextFieldRua.getText().length() >= 30) {
		    evt.consume();
	    }
    }//GEN-LAST:event_jTextFieldRuaKeyTyped

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
	    jTextFieldIdcliente.setText("");
	    jTextFieldNomeContato.setText("");
	    jTextFieldRazãoSocial.setText("");
	    jFormattedTextFieldCNPJ.setText("");
	    jTextFieldCidade.setText("");
	    jTextFieldRua.setText("");
	    jComboBoxEstado.setSelectedIndex(0);
	    jTextFieldCep.setText("");
	    jTextFieldEmail.setText("");
	    jTextFieldTelefone.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
	    String validacao = "Campos Obrigatórios";
	    int flag = 0;

	    if (jTextFieldNomeContato.getText().isEmpty()) {
		    validacao = validacao + "\n * Preencha o campo Nome Contato";
		    flag = 1;
	    }
	    if (jTextFieldRazãoSocial.getText().isEmpty()) {
		    validacao = validacao + "\n * Preencha o campo Razão Social";
		    flag = 1;
	    }
	    if (jFormattedTextFieldCNPJ.getText().equals("  .   .   /    -  ")) {
		    validacao = validacao + "\n * Preencha o campo CNPJ";
		    flag = 1;
	    }
	    if (jTextFieldCidade.getText().isEmpty()) {
		    validacao = validacao + "\n * Preencha o campo Cidade";
		    flag = 1;
	    }
	    if (jTextFieldRua.getText().isEmpty()) {
		    validacao = validacao + "\n * Preencha o campo Rua";
		    flag = 1;
	    }
	    if (jComboBoxEstado.getSelectedIndex() == 0) {
		    validacao = validacao + "\n * Escolha  o seu Estado";
		    flag = 1;
	    }
	    if (jTextFieldCep.getText().isEmpty()) {
		    validacao = validacao + "\n * Preencha o campo CEP";
		    flag = 1;
	    }
	    if (jTextFieldEmail.getText().isEmpty()) {
		    validacao = validacao + "\n * Preencha o campo E-mail";
		    flag = 1;
	    }
	    if (jTextFieldTelefone.getText().isEmpty()) {
		    validacao = validacao + "\n * Preencha o campo Telefone";
		    flag = 1;
	    }
	    if (flag == 1) {

		    JOptionPane.showMessageDialog(null, validacao);
	    } else {

		    if (jTable3.getSelectedRow() != -1) {

			    Cliente cliente = new Cliente();
			    Connection con = new Conexao().AbrirConexao();
			    ClienteController cc = new ClienteController(con);

			    cliente.setEstado(jComboBoxEstado.getSelectedIndex() + "");
			    cliente.setCep(jTextFieldCep.getText());
			    cliente.setRazaoSocial(jTextFieldRazãoSocial.getText());
			    cliente.setCnpj(jFormattedTextFieldCNPJ.getText());
			    cliente.setEmail(jTextFieldEmail.getText());
			    cliente.setTelefone(jTextFieldCep.getText());
			    cliente.setRua(jTextFieldRua.getText());
			    cliente.setCidade(jTextFieldCidade.getText());
			    cliente.setNomeContato(jTextFieldNomeContato.getText());

			    cc.alterarCliente(cliente, jTextFieldIdcliente.getText());

			    javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) jTable3.getModel();
			    dtm.setValueAt(Integer.parseInt(jTextFieldIdcliente.getText()), jTable3.getSelectedRow(), 0);
			    dtm.setValueAt(jTextFieldNomeContato.getText(), jTable3.getSelectedRow(), 1);
			    dtm.setValueAt(jTextFieldRazãoSocial.getText(), jTable3.getSelectedRow(), 2);
			    dtm.setValueAt(jFormattedTextFieldCNPJ.getText(), jTable3.getSelectedRow(), 3);
			    dtm.setValueAt(jTextFieldCidade.getText(), jTable3.getSelectedRow(), 4);
			    dtm.setValueAt(jTextFieldRua.getText(), jTable3.getSelectedRow(), 5);
			    dtm.setValueAt(jComboBoxEstado.getSelectedItem(), jTable3.getSelectedRow(), 6);
			    dtm.setValueAt(jTextFieldCep.getText(), jTable3.getSelectedRow(), 7);
			    dtm.setValueAt(jTextFieldEmail.getText(), jTable3.getSelectedRow(), 8);
			    dtm.setValueAt(jTextFieldTelefone.getText(), jTable3.getSelectedRow(), 9);

			    JOptionPane.showMessageDialog(null, "Cadastro alterado com sucesso");
		    }
	    }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

	    //  JanelaPrincipal.colocarPanelPrincipal();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jTextFieldRazãoSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRazãoSocialActionPerformed
	    // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRazãoSocialActionPerformed

    private void jTextFieldRazãoSocialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRazãoSocialKeyTyped
	    // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRazãoSocialKeyTyped

    private void jTextFieldCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCepActionPerformed
	    // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCepActionPerformed

    private void jTextFieldCepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCepKeyTyped
	    // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCepKeyTyped

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
	    // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyTyped
	    // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailKeyTyped

    private void jComboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoActionPerformed
	    // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstadoActionPerformed

    private void jTextFieldIdclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdclienteActionPerformed
	    // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdclienteActionPerformed

    private void jButtonLimparBusca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparBusca2ActionPerformed
	    jTextFieldBusca2.setText("");
	    DefaultTableModel dtm = (DefaultTableModel) jTable3.getModel();
	    for (int i = dtm.getRowCount(); i > 0; i--) {
		    dtm.removeRow(i - 1);
	    }
	    // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimparBusca2ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
	    int[] l = jTable3.getSelectedRows();
	    if (l.length == 1) {
		    try {

			    jTextFieldIdcliente.setText(jTable3.getValueAt(l[0], 0) + "");

			    jTextFieldNomeContato.setText(jTable3.getValueAt(l[0], 1) + "");
			    jTextFieldRazãoSocial.setText(jTable3.getValueAt(l[0], 2) + "");

			    jFormattedTextFieldCNPJ.setText(jTable3.getValueAt(l[0], 3) + "");
			    jTextFieldCidade.setText(jTable3.getValueAt(l[0], 4) + "");
			    jTextFieldRua.setText(jTable3.getValueAt(l[0], 5) + "");

			    jComboBoxEstado.setSelectedItem(jTable3.getValueAt(l[0], 6) + "");

			    jTextFieldCep.setText(jTable3.getValueAt(l[0], 7) + "");
			    jTextFieldEmail.setText(jTable3.getValueAt(l[0], 8) + "");

			    jTextFieldTelefone.setText(jTable3.getValueAt(l[0], 9) + "");

			    //copie e cole o comando acima para cada componente TextField do form. (Não esqueça de seguir a numeração no final)
		    } catch (Exception e) {
			    JOptionPane.showMessageDialog(null, "Ocorreu um erro \n" + e.getMessage());
		    }
	    }

	    // TODO add your handling code here:
    }//GEN-LAST:event_jTable3MouseClicked

    private void jTable3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable3KeyReleased
	    //jTable1MouseClicked(null);
	    // TODO add your handling code here:
    }//GEN-LAST:event_jTable3KeyReleased

    private void jButtonPesquisar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisar2ActionPerformed
	    try {

		    Connection con = new Conexao().AbrirConexao();
		    ClienteController cc = new ClienteController(con);

		    List<Cliente> cliente = (jTextFieldBusca2.getText().equals("")) ? cc.listarTodosClientes() : cc.listarClientesEspecificosRazaoSocial(jTextFieldBusca2.getText(), 0);

		    DefaultTableModel dtm = (DefaultTableModel) jTable3.getModel();
		    for (int i = dtm.getRowCount(); i > 0; i--) {
			    dtm.removeRow(i - 1);
		    }
		    
		    if (cliente.isEmpty()) {
			    
			    JOptionPane.showMessageDialog(null, "Não existem dados para essa busca");
		    }
		    
		    for (int i = 0; i < cliente.size(); i++) {
			    dtm.addRow(new Object[]{
				    cliente.get(i).getIdCliente(),
				    cliente.get(i).getNomeContato(),
				    cliente.get(i).getRazaoSocial(),
				    cliente.get(i).getCnpj(),
				    cliente.get(i).getCidade(),
				    cliente.get(i).getRua(),
				    cliente.get(i).getEstado(),
				    cliente.get(i).getCep(),
				    cliente.get(i).getEmail(),
				    cliente.get(i).getTelefone(),});
		    }
	    } catch (HeadlessException ex) {
		    JOptionPane.showMessageDialog(null, ex.getMessage());
	    }
	    // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPesquisar2ActionPerformed

    private void jTextFieldCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCidadeActionPerformed
	    // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCidadeActionPerformed

    private void jTextFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneActionPerformed
	    // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefoneActionPerformed


      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton jButtonAlterar;
      private javax.swing.JButton jButtonLimpar;
      private javax.swing.JButton jButtonLimparBusca2;
      private javax.swing.JButton jButtonPesquisar2;
      private javax.swing.JComboBox jComboBoxEstado;
      private javax.swing.JFormattedTextField jFormattedTextFieldCNPJ;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel10;
      private javax.swing.JLabel jLabel11;
      private javax.swing.JLabel jLabel12;
      private javax.swing.JLabel jLabel13;
      private javax.swing.JLabel jLabel14;
      private javax.swing.JLabel jLabel15;
      private javax.swing.JLabel jLabel17;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel5;
      private javax.swing.JLabel jLabel6;
      private javax.swing.JLabel jLabel7;
      private javax.swing.JLabel jLabel9;
      private javax.swing.JPanel jPanel1;
      private javax.swing.JPanel jPanel2;
      private javax.swing.JPanel jPanel3;
      private javax.swing.JPanel jPanel4;
      private javax.swing.JPanel jPanel6;
      private javax.swing.JScrollPane jScrollPane3;
      private javax.swing.JTable jTable3;
      private javax.swing.JTextField jTextFieldBusca2;
      private javax.swing.JTextField jTextFieldCep;
      private javax.swing.JTextField jTextFieldCidade;
      private javax.swing.JTextField jTextFieldEmail;
      private javax.swing.JTextField jTextFieldIdcliente;
      private javax.swing.JTextField jTextFieldNomeContato;
      private javax.swing.JTextField jTextFieldRazãoSocial;
      private javax.swing.JTextField jTextFieldRua;
      private javax.swing.JTextField jTextFieldTelefone;
      // End of variables declaration//GEN-END:variables
}
