/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Cliente;

import Controller.ClienteController;
import Controller.Conexao;
import Model.Cliente;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author LucasMarcon
 */
public class inserirCliente1 extends javax.swing.JPanel {

	private final Cliente cliente = new Cliente();
	private final Connection con = new Conexao().AbrirConexao();
	private final ClienteController cc = new ClienteController(con);
	
	/**
	 * Creates new form inserirCliente1
	 */
	public inserirCliente1() {
		
		initComponents();

		int index1 = 0;
		for (String listarEstado : cc.listarEstados()) {
			
			comboBoxEstado.insertItemAt(listarEstado, index1);
			index1++;
		}
		
		int index2 = 0;
		for (String listarCidade : cc.listarCidades()) {
			
			comboBoxCidade.insertItemAt(listarCidade, index2);
			index2++;
		}
	}

	/**
	 * This method is called from within the
	 * constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The
	 * content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelNomeContato = new javax.swing.JLabel();
        labelRazaoSocial = new javax.swing.JLabel();
        labelRua = new javax.swing.JLabel();
        labelCnpj = new javax.swing.JLabel();
        labelCidade = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        labelCep = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        textFieldEmail = new javax.swing.JTextField();
        separadorEmail = new javax.swing.JSeparator();
        textFieldRua = new javax.swing.JTextField();
        separadorRua = new javax.swing.JSeparator();
        textFieldRazaoSocial = new javax.swing.JTextField();
        separadorRazaoSocial = new javax.swing.JSeparator();
        textFieldCnpj = new javax.swing.JTextField();
        separadorEstado = new javax.swing.JSeparator();
        textFieldNomeContato = new javax.swing.JTextField();
        separadorNomeContato = new javax.swing.JSeparator();
        textFieldCep = new javax.swing.JTextField();
        separadorCep = new javax.swing.JSeparator();
        comboBoxEstado = new javax.swing.JComboBox<>();
        comboBoxCidade = new javax.swing.JComboBox<>();
        separadorCnpj = new javax.swing.JSeparator();
        separadorCidade = new javax.swing.JSeparator();
        textFieldTelefone = new javax.swing.JTextField();
        separadorTelefone = new javax.swing.JSeparator();
        botaoLimpar = new javax.swing.JButton();
        botaoCadastrar = new javax.swing.JButton();

        painelPrincipal.setBackground(new java.awt.Color(0, 153, 153));

        labelTitulo.setBackground(new java.awt.Color(224, 224, 224));
        labelTitulo.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(224, 224, 224));
        labelTitulo.setText("Cadastro de Clientes");

        labelNomeContato.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        labelNomeContato.setText("<html>Nome Contato:<font color=\"red\"><b>*</b></font>");

        labelRazaoSocial.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        labelRazaoSocial.setText("<html>Razão Social:<font color=\"red\"><b>*</b></font>");

        labelRua.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        labelRua.setText("<html>Rua:<font color=\"red\"><b>*</b></font>");

        labelCnpj.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        labelCnpj.setText("<html>Cnpj:<font color=\"red\"><b>*</b></font>");

        labelCidade.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        labelCidade.setText("Cidade: ");

        labelEstado.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        labelEstado.setText("Estado: ");

        labelCep.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        labelCep.setText("<html>Cep:<font color=\"red\"><b>*</b></font> ");

        labelEmail.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        labelEmail.setText("<html>E-mail:<font color=\"red\"><b>*</b></font>");

        labelTelefone.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        labelTelefone.setText("<html>Telefone:<font color=\"red\"><b>*</b></font>");

        textFieldEmail.setBackground(new java.awt.Color(0, 153, 153));
        textFieldEmail.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        textFieldEmail.setBorder(null);
        textFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEmailActionPerformed(evt);
            }
        });

        separadorEmail.setBackground(new java.awt.Color(224, 224, 224));

        textFieldRua.setBackground(new java.awt.Color(0, 153, 153));
        textFieldRua.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        textFieldRua.setBorder(null);
        textFieldRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldRuaActionPerformed(evt);
            }
        });

        separadorRua.setBackground(new java.awt.Color(224, 224, 224));

        textFieldRazaoSocial.setBackground(new java.awt.Color(0, 153, 153));
        textFieldRazaoSocial.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        textFieldRazaoSocial.setBorder(null);
        textFieldRazaoSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldRazaoSocialActionPerformed(evt);
            }
        });

        separadorRazaoSocial.setBackground(new java.awt.Color(224, 224, 224));

        textFieldCnpj.setBackground(new java.awt.Color(0, 153, 153));
        textFieldCnpj.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        textFieldCnpj.setBorder(null);
        textFieldCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCnpjActionPerformed(evt);
            }
        });

        textFieldNomeContato.setBackground(new java.awt.Color(0, 153, 153));
        textFieldNomeContato.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        textFieldNomeContato.setBorder(null);
        textFieldNomeContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNomeContatoActionPerformed(evt);
            }
        });

        separadorNomeContato.setBackground(new java.awt.Color(224, 224, 224));

        textFieldCep.setBackground(new java.awt.Color(0, 153, 153));
        textFieldCep.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        textFieldCep.setBorder(null);
        textFieldCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCepActionPerformed(evt);
            }
        });

        separadorCep.setBackground(new java.awt.Color(224, 224, 224));

        comboBoxEstado.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        comboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione seu estado" }));
        comboBoxEstado.setBorder(null);

        comboBoxCidade.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        comboBoxCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione sua cidade" }));
        comboBoxCidade.setBorder(null);

        separadorCnpj.setBackground(new java.awt.Color(224, 224, 224));

        textFieldTelefone.setBackground(new java.awt.Color(0, 153, 153));
        textFieldTelefone.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        textFieldTelefone.setBorder(null);
        textFieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTelefoneActionPerformed(evt);
            }
        });

        separadorTelefone.setBackground(new java.awt.Color(224, 224, 224));

        botaoLimpar.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        botaoCadastrar.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(labelTitulo))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(labelNomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169)
                        .addComponent(labelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(textFieldNomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(textFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(separadorNomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(separadorTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(labelRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186)
                        .addComponent(labelRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(labelCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(246, 246, 246)
                        .addComponent(labelCidade))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(separadorCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(separadorCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(233, 233, 233)
                        .addComponent(labelEstado))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(separadorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(separadorEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(labelCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(separadorCep, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(botaoCadastrar)
                        .addGap(40, 40, 40)
                        .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                                .addComponent(textFieldRazaoSocial)
                                .addGap(40, 40, 40)
                                .addComponent(textFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelPrincipalLayout.createSequentialGroup()
                                .addComponent(separadorRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(separadorRua, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(260, 260, 260))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelTitulo)
                .addGap(12, 12, 12)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldNomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separadorNomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separadorTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separadorRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separadorRua, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCidade))
                .addGap(5, 5, 5)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addComponent(textFieldCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(separadorCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(separadorCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEstado))
                .addGap(5, 5, 5)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(separadorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(separadorEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(labelCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addComponent(textFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(separadorCep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoCadastrar)
                    .addComponent(botaoLimpar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

      private void textFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEmailActionPerformed
		// TODO add your handling code here:
      }//GEN-LAST:event_textFieldEmailActionPerformed

      private void textFieldRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldRuaActionPerformed
		// TODO add your handling code here:
      }//GEN-LAST:event_textFieldRuaActionPerformed

      private void textFieldRazaoSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldRazaoSocialActionPerformed
		// TODO add your handling code here:
      }//GEN-LAST:event_textFieldRazaoSocialActionPerformed

      private void textFieldCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCnpjActionPerformed
		// TODO add your handling code here:
      }//GEN-LAST:event_textFieldCnpjActionPerformed

      private void textFieldNomeContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNomeContatoActionPerformed
		// TODO add your handling code here:
      }//GEN-LAST:event_textFieldNomeContatoActionPerformed

      private void textFieldCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCepActionPerformed
		// TODO add your handling code here:
      }//GEN-LAST:event_textFieldCepActionPerformed

      private void textFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTelefoneActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_textFieldTelefoneActionPerformed

      private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
		
		textFieldCep.setText("");
		textFieldCnpj.setText("");
		textFieldEmail.setText("");
		textFieldNomeContato.setText("");
		textFieldRazaoSocial.setText("");
		textFieldRua.setText("");
		textFieldTelefone.setText("");
		comboBoxEstado.setSelectedIndex(0);
		comboBoxCidade.setSelectedIndex(0);
      }//GEN-LAST:event_botaoLimparActionPerformed

      private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
		
		boolean campoVazio = (textFieldCep.getText().isEmpty() ? 
			               (textFieldCnpj.getText().isEmpty() ? 
			               (textFieldEmail.getText().isEmpty() ? 
			               (textFieldNomeContato.getText().isEmpty() ? 
			               (textFieldRazaoSocial.getText().isEmpty() ? 
			               (textFieldRua.getText().isEmpty() ? 
			               (textFieldTelefone.getText().isEmpty()) : false) : false) : false) : false) : false) : false);
		
		if (campoVazio) {
			
			JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!");
		} else {
			
			cliente.setCep(textFieldCep.getText());
			cliente.setCidade(comboBoxCidade.getSelectedIndex()+ "");
			cliente.setCnpj(textFieldCnpj.getText());
			cliente.setEmail(textFieldEmail.getText());
			cliente.setEstado(comboBoxEstado.getSelectedIndex()+ "");
			cliente.setNomeContato(textFieldNomeContato.getText());
			cliente.setRazaoSocial(textFieldRazaoSocial.getText());
			cliente.setRua(textFieldRua.getText());
			cliente.setTelefone(textFieldTelefone.getText());
			
			cc.inserirCliente(cliente);
			
			JOptionPane.showMessageDialog(null, "Cliente inserido com sucesso!");
		}
      }//GEN-LAST:event_botaoCadastrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JComboBox<String> comboBoxCidade;
    private javax.swing.JComboBox<String> comboBoxEstado;
    private javax.swing.JLabel labelCep;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelCnpj;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelNomeContato;
    private javax.swing.JLabel labelRazaoSocial;
    private javax.swing.JLabel labelRua;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JSeparator separadorCep;
    private javax.swing.JSeparator separadorCidade;
    private javax.swing.JSeparator separadorCnpj;
    private javax.swing.JSeparator separadorEmail;
    private javax.swing.JSeparator separadorEstado;
    private javax.swing.JSeparator separadorNomeContato;
    private javax.swing.JSeparator separadorRazaoSocial;
    private javax.swing.JSeparator separadorRua;
    private javax.swing.JSeparator separadorTelefone;
    private javax.swing.JTextField textFieldCep;
    private javax.swing.JTextField textFieldCnpj;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldNomeContato;
    private javax.swing.JTextField textFieldRazaoSocial;
    private javax.swing.JTextField textFieldRua;
    private javax.swing.JTextField textFieldTelefone;
    // End of variables declaration//GEN-END:variables
}
