/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SalvarServiços.java
 *
 * Created on 16/06/2014, 19:04:32
 */
package Visual;

import Controle.servicosdados;
import Model.servicos;
import java.sql.SQLException;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author helio
 */
public class SalvarServiços extends javax.swing.JPanel {

    /** Creates new form SalvarServiços */
    public SalvarServiços() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jTextFieldSetor = new javax.swing.JTextField();
        jTextFieldValorUnit = new javax.swing.JTextField();
        jTextFieldQuant = new javax.swing.JTextField();
        jTextFieldValorTotal = new javax.swing.JTextField();
        jTextFieldFuncionario = new javax.swing.JTextField();
        jComboBoxDia = new javax.swing.JComboBox();
        jComboBoxMes = new javax.swing.JComboBox();
        jComboBoxAno = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jButtonLimpar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCalculoPrecoTotal = new javax.swing.JButton();
        jComboBoxTipoServiço = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 102));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 3, true), "Cadastro de Serviço", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(51, 102, 0))); // NOI18N

        jLabel1.setText("<html>Nome do Cliente:<font color=\"red\"><b>*</b></font>");

        jLabel2.setText("<html>Tipo de Seviço:<font color=\"red\"><b>*</b></font>");

        jLabel3.setText("<html>Setor<font color=\"red\"><b>*</b></font>");

        jLabel4.setText("<html>Valor Unitário:<font color=\"red\"><b>*</b></font>");

        jLabel5.setText("<html>Quantidade:<font color=\"red\"><b>*</b></font>");

        jLabel6.setText("Valor Total:");

        jLabel7.setText("<html>Data do Serviço:<font color=\"red\"><b>*</b></font>");

        jLabel8.setText("<html>Funcionário:<font color=\"red\"><b>*</b></font>");

        jTextFieldNomeCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomeClienteKeyTyped(evt);
            }
        });

        jTextFieldSetor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSetorKeyTyped(evt);
            }
        });

        jTextFieldValorUnit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldValorUnitFocusLost(evt);
            }
        });
        jTextFieldValorUnit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldValorUnitKeyTyped(evt);
            }
        });

        jTextFieldQuant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldQuantKeyTyped(evt);
            }
        });

        jTextFieldValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorTotalActionPerformed(evt);
            }
        });
        jTextFieldValorTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldValorTotalFocusLost(evt);
            }
        });
        jTextFieldValorTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldValorTotalKeyTyped(evt);
            }
        });

        jTextFieldFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFuncionarioKeyTyped(evt);
            }
        });

        jComboBoxDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mês", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        jComboBoxAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ano" }));

        jLabel9.setText("<html><font color=\"red\"><b>*</b></font>Campos Obrigatórios");

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCalculoPrecoTotal.setText("Calcular Preço Total");
        jButtonCalculoPrecoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculoPrecoTotalActionPerformed(evt);
            }
        });

        jComboBoxTipoServiço.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione ", "Eletricista", " Bombeiro Hidráulico", "Pintura ", "Marcenaria", "Pedreiro", "Jardinagem ", "Montagem e Reparos" }));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fechar_1.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jTextFieldValorUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                    .addComponent(jButtonCalculoPrecoTotal))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jTextFieldQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(36, 36, 36)))
                    .addComponent(jComboBoxTipoServiço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonLimpar)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonSalvar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldSetor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(421, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxTipoServiço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValorUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCalculoPrecoTotal))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonSalvar))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        GregorianCalendar data = new GregorianCalendar();
        int ano = data.get (GregorianCalendar.YEAR);

        while (ano>=1900){

            jComboBoxAno.addItem(""+ano);
            ano--;
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jTextFieldNomeClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeClienteKeyTyped
    if (jTextFieldNomeCliente.getText().length() >= 60) {
        evt.consume();
    }
}//GEN-LAST:event_jTextFieldNomeClienteKeyTyped

private void jTextFieldSetorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSetorKeyTyped
    if (jTextFieldSetor.getText().length() >= 60) {
        evt.consume();
    }
}//GEN-LAST:event_jTextFieldSetorKeyTyped

private void jTextFieldValorUnitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldValorUnitFocusLost
if(!jTextFieldValorUnit.getText().contains(".")){
jTextFieldValorUnit.setText(jTextFieldValorUnit.getText()+".00");
}

if(jTextFieldValorUnit.getText().substring(0,1).equals(".")){
jTextFieldValorUnit.setText("0"+jTextFieldValorUnit.getText());
}

if (jTextFieldValorUnit.getText().charAt(jTextFieldValorUnit.getText().length()-1)=='.'){
jTextFieldValorUnit.setText(jTextFieldValorUnit.getText()+"0");
}
}//GEN-LAST:event_jTextFieldValorUnitFocusLost

private void jTextFieldValorUnitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValorUnitKeyTyped
String caracteres="0123456789.,";

if(!caracteres.contains(evt.getKeyChar()+"")){
    evt.consume();
}

if(",".equals(evt.getKeyChar()+"")){
    evt.setKeyChar('.');
}

if((jTextFieldValorUnit.getText().contains("."))
        &&(".".equals(evt.getKeyChar()+""))) {
    evt.consume();
}


    if (jTextFieldValorUnit.getText().length() >= 8) {
        evt.consume();
    }
}//GEN-LAST:event_jTextFieldValorUnitKeyTyped

private void jTextFieldQuantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQuantKeyTyped
String caracteres = "0987654321";
    if (!caracteres.contains(evt.getKeyChar() + "")) {
        evt.consume();
    }
    
        if (jTextFieldQuant.getText().length() >= 9) {
        evt.consume();
    }
}//GEN-LAST:event_jTextFieldQuantKeyTyped

private void jTextFieldValorTotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldValorTotalFocusLost
if(!jTextFieldValorTotal.getText().contains(".")){
jTextFieldValorTotal.setText(jTextFieldValorTotal.getText()+".00");
}

if(jTextFieldValorTotal.getText().substring(0,1).equals(".")){
jTextFieldValorTotal.setText("0"+jTextFieldValorTotal.getText());
}

if (jTextFieldValorTotal.getText().charAt(jTextFieldValorTotal.getText().length()-1)=='.'){
jTextFieldValorTotal.setText(jTextFieldValorTotal.getText()+"0");
}
}//GEN-LAST:event_jTextFieldValorTotalFocusLost

private void jTextFieldValorTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValorTotalKeyTyped
String caracteres="0123456789.,";

if(!caracteres.contains(evt.getKeyChar()+"")){
    evt.consume();
}

if(",".equals(evt.getKeyChar()+"")){
    evt.setKeyChar('.');
}

if((jTextFieldValorTotal.getText().contains("."))
        &&(".".equals(evt.getKeyChar()+""))) {
    evt.consume();
}


    if (jTextFieldValorTotal.getText().length() >= 8) {
        evt.consume();
    }
}//GEN-LAST:event_jTextFieldValorTotalKeyTyped

private void jTextFieldFuncionarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFuncionarioKeyTyped
    if (jTextFieldFuncionario.getText().length() >= 60) {
        evt.consume();
    }
}//GEN-LAST:event_jTextFieldFuncionarioKeyTyped

private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
    jTextFieldNomeCliente.setText("");
    jTextFieldSetor.setText("");
    jComboBoxTipoServiço.setSelectedIndex(0);
    jTextFieldValorUnit.setText("");
    jTextFieldQuant.setText("");
    jTextFieldValorTotal.setText("");
    jComboBoxDia.setSelectedIndex(0);
    jComboBoxMes.setSelectedIndex(0);
    jComboBoxAno.setSelectedIndex(0);
    jTextFieldFuncionario.setText("");
}//GEN-LAST:event_jButtonLimparActionPerformed

private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
String validacao = "Campos Obrigatórios";
    int flag = 0;

    if (jTextFieldNomeCliente.getText().isEmpty()) {
        validacao = validacao + "\n * Preencha o campo nome do cliente";
        flag = 1;
    }

   
    if (jComboBoxTipoServiço.getSelectedIndex() == 0){
        validacao = validacao + "\n * Preencha o campo tipo de serviço";
        flag = 1;
    }
     if (jTextFieldFuncionario.getText().isEmpty()) {
        validacao = validacao + "\n * Preencha o campo funcionário";
        flag = 1;
    }
     if (jTextFieldSetor.getText().isEmpty()) {
        validacao = validacao + "\n * Preencha o campo setor";
        flag = 1;
    }
    
    if (jTextFieldValorUnit.getText().isEmpty()) {
        validacao = validacao + "\n * Preencha o campo valor unitário";
        flag = 1;
    }
    
    if (jTextFieldQuant.getText().isEmpty()) {
        validacao = validacao + "\n * Preencha o campo quantidade";
        flag = 1;
    }
    
    if (jComboBoxDia.getSelectedIndex() == 0){
        validacao = validacao + "\n * Preencha o campo dia";
        flag = 1;
    }
    
    if (jComboBoxMes.getSelectedIndex() == 0){
        validacao = validacao + "\n * Preencha o campo mês";
        flag = 1;
    }
    
    if (jComboBoxAno.getSelectedIndex() == 0){
        validacao = validacao + "\n * Preencha o campo ano";
        flag = 1;
    }

   
    
        if (flag == 1){
        JOptionPane.showMessageDialog(null, validacao);
    } else {

            //  Botão salvar
        try {
            servicos X = new servicos();     //PACOTE METODOS

            servicosdados bancodados = new servicosdados();     //PACOTE BANCODADOS

//ATENÇÃO O EXEMPLO ABAIXO É PARA COMPONENTES JTEXTFIELD

	X.setNomecliente(jTextFieldNomeCliente.getText());
        X.setTiposervico(jComboBoxTipoServiço.getSelectedItem()+"");
        X.setSetor(jTextFieldSetor.getText());
        X.setFuncionario(jTextFieldFuncionario.getText());
        X.setValorunitario(Float.parseFloat(jTextFieldValorUnit.getText()));
        X.setQuantidade(Integer.parseInt(jTextFieldQuant.getText()));
        X.setValortotal(Float.parseFloat(jTextFieldValorTotal.getText()));
        X.setDataservico(jComboBoxDia.getSelectedItem()+" de "+jComboBoxMes.getSelectedItem()+" de "+jComboBoxAno.getSelectedItem()+"");
	
	
	bancodados.adiciona(X);
            	JOptionPane.showMessageDialog(null, "Salvo com sucesso");
        } 	catch (SQLException ex) {
            	JOptionPane.showMessageDialog(null, "Erro no banco:\n" + ex.getMessage());
        } 	catch (Exception ex) {
            	JOptionPane.showMessageDialog(null, "Erro:\n" + ex.getMessage());
        }
            
        }
}//GEN-LAST:event_jButtonSalvarActionPerformed

private void jButtonCalculoPrecoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculoPrecoTotalActionPerformed
int quant;
float valortotal, valorunit;

quant=Integer.parseInt(jTextFieldQuant.getText());
valorunit=Float.parseFloat(jTextFieldValorUnit.getText());

valortotal=valorunit*quant;

jTextFieldValorTotal.setText(valortotal+"");
}//GEN-LAST:event_jButtonCalculoPrecoTotalActionPerformed

private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

    JanelaPrincipal.colocarPanelPrincipal();// TODO add your handling code here:
}//GEN-LAST:event_jLabel10MouseClicked

private void jTextFieldValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorTotalActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextFieldValorTotalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalculoPrecoTotal;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxAno;
    private javax.swing.JComboBox jComboBoxDia;
    private javax.swing.JComboBox jComboBoxMes;
    private javax.swing.JComboBox jComboBoxTipoServiço;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldFuncionario;
    private javax.swing.JTextField jTextFieldNomeCliente;
    private javax.swing.JTextField jTextFieldQuant;
    private javax.swing.JTextField jTextFieldSetor;
    private javax.swing.JTextField jTextFieldValorTotal;
    private javax.swing.JTextField jTextFieldValorUnit;
    // End of variables declaration//GEN-END:variables
}
